# Organize IGRF output file

## Description

This program organizes the IGRF13 output file (from the software Geomag70.exe (Windows versions) available at <https://www.ngdc.noaa.gov/IAGA/vmod/igrf.html>) in order to create an IGRF13 dataframe. The changes are:
- The substitution of spaces for commas in order to create a truly csv file
- The letters "d" for degree and "m" for minute were deleted from the D_deg, I_deg, D_min and I_min columns
- The letter "M" in the altitude column (for meters) was removed. The column header changed from Altitude to Altitude_m, to indicate that the unit for the altitude is meters

In [1]:
# Import modules
import mestrado_module as mm
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
# Paths
input_folder: Path = Path(mm.path_pipeline_04_igrf_calc)
output_folder: Path = Path(mm.path_pipeline_04_igrf_calc)

# Files
input_file: Path = Path(mm.output_4b_geomag_file) #result from geomag
output_file: Path = Path(mm.output_4c_code_igrf_database) #igrf database

# Repeat station data
rs_file: Path = Path(mm.output_3_code_rs_database)
rs_folder: Path = Path(mm.path_pipeline_03_rs_database_creation)

## Read data

In [3]:
# Load IGRF data with Pandas
igrf_df = pd.read_csv(input_folder / input_file, sep="\s+", engine="python")
igrf_df

,Date,Coord-System,Altitude,Latitude,Longitude,D_deg,D_min,I_deg,I_min,H_nT,...,Y_nT,Z_nT,F_nT,dD_min,dI_min,dH_nT,dX_nT,dY_nT,dZ_nT,dF_nT
0,1958.529,D,M182.464,-7.637,-72.670,2d,47m,11d,10m,29072.2,...,1412.5,5735.2,29632.5,-6.9,-3.1,-59.5,-56.7,-60.9,-38.5,-65.8
1,1965.848,D,M182.464,-7.637,-72.670,1d,55m,10d,55m,28605.3,...,959.8,5519.5,29132.9,-7.4,-0.8,-73.5,-71.5,-63.7,-20.8,-76.1
2,1978.640,D,M195.6,-7.620,-72.670,0d,9m,10d,48m,27813.9,...,72.2,5309.1,28316.1,-10.4,1.4,-46.8,-46.8,-84.3,2.4,-45.6
3,1986.279,D,M196.508,-7.599,-72.770,-1d,5m,10d,33m,27428.6,...,-520.7,5109.1,27900.4,-10.2,-4.3,-51.2,-52.9,-80.1,-44.6,-58.5
4,1989.503,D,M196.508,-7.599,-72.770,-1d,38m,10d,19m,27264.3,...,-778.9,4965.3,27712.7,-10.3,-4.3,-50.4,-52.9,-80.1,-44.6,-57.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,1985.119,D,M240.299,-10.727,-48.408,-18d,5m,-7d,1m,24935.1,...,-7741.6,-3070.7,25123.5,-6.3,-19.5,-58.2,-69.4,-25.0,-136.5,-40.6
1078,1986.670,D,M240.299,-10.727,-48.408,-18d,15m,-7d,32m,24844.9,...,-7780.4,-3282.4,25060.8,-6.3,-19.6,-58.0,-69.4,-25.0,-136.5,-39.2
1079,1995.817,D,M240.299,-10.727,-48.408,-19d,15m,-10d,37m,24299.2,...,-8009.9,-4551.7,24721.8,-6.1,-20.9,-60.2,-71.0,-20.9,-141.1,-32.7
1080,2003.702,D,M256.835,-10.721,-48.401,-20d,2m,-13d,21m,23824.7,...,-8162.8,-5656.0,24486.8,-5.9,-21.0,-60.5,-70.8,-17.2,-139.1,-26.3
1081,1970.729,D,M249.44,-9.242,-48.530,-16d,0m,0d,-1m,26131.5,...,-7204.4,-9.8,26131.5,-7.7,-15.5,-56.8,-70.7,-40.4,-117.6,-56.5

In [4]:
# Read RS data
rs_df = pd.read_csv(rs_folder / rs_file)
rs_df

,Code,Lat_dd,Lon_dd,Alt_m,Time_dy,D_dd,I_dd,H_nT,X_nT,Y_nT,...,State,Region,RS_name,Calculated_X,Calculated_Y,Calculated_Z,TTB_distances_km,VSS_distances_km,Closest_OBS,N_occupations
0,AC_CZS,-7.637,-72.670,182.464,1958.529,2.683,11.281,29097.0,29065.0,1362.0,...,AC,N,CRUZEIRO DO SUL,29065.847,1362.067,5804.269,2770.494,3511.151,TTB,6
1,AC_CZS,-7.637,-72.670,182.464,1965.848,1.824,11.277,28662.0,28648.0,912.0,...,AC,N,CRUZEIRO DO SUL,28648.198,912.318,5715.412,2770.494,3511.151,TTB,6
2,AC_CZS,-7.620,-72.670,195.600,1978.640,-0.035,11.026,27835.0,27835.0,-17.0,...,AC,N,CRUZEIRO DO SUL,27835.502,-17.004,5423.784,2770.044,3512.127,TTB,6
3,AC_CZS,-7.599,-72.770,196.508,1986.279,-1.343,10.685,27402.0,27394.0,-642.0,...,AC,N,CRUZEIRO DO SUL,27394.968,-642.249,5170.325,2780.199,3522.772,TTB,6
4,AC_CZS,-7.599,-72.770,196.508,1989.503,-1.847,10.468,27222.0,27208.0,-877.0,...,AC,N,CRUZEIRO DO SUL,27208.116,-877.391,5029.623,2780.199,3522.772,TTB,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,TO_PNL,-10.727,-48.408,240.299,1985.119,-18.142,-7.084,24938.0,23698.0,-7765.0,...,TO,N,PORTO NACIONAL,23698.435,-7765.075,-3099.141,1058.862,1393.116,TTB,9
1078,TO_PNL,-10.727,-48.408,240.299,1986.670,-18.325,-7.556,24865.0,23604.0,-7817.0,...,TO,N,PORTO NACIONAL,23604.245,-7817.785,-3298.293,1058.862,1393.116,TTB,9
1079,TO_PNL,-10.727,-48.408,240.299,1995.817,-19.315,-10.562,24358.0,22987.0,-8056.0,...,TO,N,PORTO NACIONAL,22987.174,-8056.751,-4541.793,1058.862,1393.116,TTB,9
1080,TO_PNL,-10.721,-48.401,256.835,2003.702,-20.117,-13.008,23896.0,22438.0,-8218.0,...,TO,N,PORTO NACIONAL,22438.750,-8218.967,-5520.486,1058.203,1393.470,TTB,9
1081,TO_RAB,-9.242,-48.530,249.440,1970.729,-16.148,0.093,26189.0,25156.0,-7283.0,...,TO,N,RIBEIRAO DA AGUA BRANCA,25156.680,-7283.939,42.510,893.676,1552.975,TTB,1

## Add Code column from RS dataframe into the IGRF dataframe to act as index for it

In [5]:
# Create a new dataframe to work on
merged_df = igrf_df

# Add the colum
merged_df["Code"] = rs_df["Code"]

# view
merged_df

,Date,Coord-System,Altitude,Latitude,Longitude,D_deg,D_min,I_deg,I_min,H_nT,...,Z_nT,F_nT,dD_min,dI_min,dH_nT,dX_nT,dY_nT,dZ_nT,dF_nT,Code
0,1958.529,D,M182.464,-7.637,-72.670,2d,47m,11d,10m,29072.2,...,5735.2,29632.5,-6.9,-3.1,-59.5,-56.7,-60.9,-38.5,-65.8,AC_CZS
1,1965.848,D,M182.464,-7.637,-72.670,1d,55m,10d,55m,28605.3,...,5519.5,29132.9,-7.4,-0.8,-73.5,-71.5,-63.7,-20.8,-76.1,AC_CZS
2,1978.640,D,M195.6,-7.620,-72.670,0d,9m,10d,48m,27813.9,...,5309.1,28316.1,-10.4,1.4,-46.8,-46.8,-84.3,2.4,-45.6,AC_CZS
3,1986.279,D,M196.508,-7.599,-72.770,-1d,5m,10d,33m,27428.6,...,5109.1,27900.4,-10.2,-4.3,-51.2,-52.9,-80.1,-44.6,-58.5,AC_CZS
4,1989.503,D,M196.508,-7.599,-72.770,-1d,38m,10d,19m,27264.3,...,4965.3,27712.7,-10.3,-4.3,-50.4,-52.9,-80.1,-44.6,-57.6,AC_CZS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,1985.119,D,M240.299,-10.727,-48.408,-18d,5m,-7d,1m,24935.1,...,-3070.7,25123.5,-6.3,-19.5,-58.2,-69.4,-25.0,-136.5,-40.6,TO_PNL
1078,1986.670,D,M240.299,-10.727,-48.408,-18d,15m,-7d,32m,24844.9,...,-3282.4,25060.8,-6.3,-19.6,-58.0,-69.4,-25.0,-136.5,-39.2,TO_PNL
1079,1995.817,D,M240.299,-10.727,-48.408,-19d,15m,-10d,37m,24299.2,...,-4551.7,24721.8,-6.1,-20.9,-60.2,-71.0,-20.9,-141.1,-32.7,TO_PNL
1080,2003.702,D,M256.835,-10.721,-48.401,-20d,2m,-13d,21m,23824.7,...,-5656.0,24486.8,-5.9,-21.0,-60.5,-70.8,-17.2,-139.1,-26.3,TO_PNL
1081,1970.729,D,M249.44,-9.242,-48.530,-16d,0m,0d,-1m,26131.5,...,-9.8,26131.5,-7.7,-15.5,-56.8,-70.7,-40.4,-117.6,-56.5,TO_RAB

## Change column order and drop unnecessary columns

In [6]:
new_igrf_df = merged_df[["Code", "Date", "Latitude", "Longitude", "Altitude", "D_deg", "D_min", "I_deg", "I_min", "H_nT", "X_nT", "Y_nT", "Z_nT", "F_nT", "dD_min", "dI_min", "dH_nT", "dX_nT", "dY_nT", "dZ_nT", "dF_nT"]]
new_igrf_df

,Code,Date,Latitude,Longitude,Altitude,D_deg,D_min,I_deg,I_min,H_nT,...,Y_nT,Z_nT,F_nT,dD_min,dI_min,dH_nT,dX_nT,dY_nT,dZ_nT,dF_nT
0,AC_CZS,1958.529,-7.637,-72.670,M182.464,2d,47m,11d,10m,29072.2,...,1412.5,5735.2,29632.5,-6.9,-3.1,-59.5,-56.7,-60.9,-38.5,-65.8
1,AC_CZS,1965.848,-7.637,-72.670,M182.464,1d,55m,10d,55m,28605.3,...,959.8,5519.5,29132.9,-7.4,-0.8,-73.5,-71.5,-63.7,-20.8,-76.1
2,AC_CZS,1978.640,-7.620,-72.670,M195.6,0d,9m,10d,48m,27813.9,...,72.2,5309.1,28316.1,-10.4,1.4,-46.8,-46.8,-84.3,2.4,-45.6
3,AC_CZS,1986.279,-7.599,-72.770,M196.508,-1d,5m,10d,33m,27428.6,...,-520.7,5109.1,27900.4,-10.2,-4.3,-51.2,-52.9,-80.1,-44.6,-58.5
4,AC_CZS,1989.503,-7.599,-72.770,M196.508,-1d,38m,10d,19m,27264.3,...,-778.9,4965.3,27712.7,-10.3,-4.3,-50.4,-52.9,-80.1,-44.6,-57.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,TO_PNL,1985.119,-10.727,-48.408,M240.299,-18d,5m,-7d,1m,24935.1,...,-7741.6,-3070.7,25123.5,-6.3,-19.5,-58.2,-69.4,-25.0,-136.5,-40.6
1078,TO_PNL,1986.670,-10.727,-48.408,M240.299,-18d,15m,-7d,32m,24844.9,...,-7780.4,-3282.4,25060.8,-6.3,-19.6,-58.0,-69.4,-25.0,-136.5,-39.2
1079,TO_PNL,1995.817,-10.727,-48.408,M240.299,-19d,15m,-10d,37m,24299.2,...,-8009.9,-4551.7,24721.8,-6.1,-20.9,-60.2,-71.0,-20.9,-141.1,-32.7
1080,TO_PNL,2003.702,-10.721,-48.401,M256.835,-20d,2m,-13d,21m,23824.7,...,-8162.8,-5656.0,24486.8,-5.9,-21.0,-60.5,-70.8,-17.2,-139.1,-26.3
1081,TO_RAB,1970.729,-9.242,-48.530,M249.44,-16d,0m,0d,-1m,26131.5,...,-7204.4,-9.8,26131.5,-7.7,-15.5,-56.8,-70.7,-40.4,-117.6,-56.5

## Delete the "M", "d", and "min" words from the database

In [7]:
# Create variables that hold the new values
new_altitude = new_igrf_df["Altitude"].str.replace("M", "")
new_d_deg = new_igrf_df["D_deg"].str.replace("d", "")
new_d_min = new_igrf_df["D_min"].str.replace("m", "")
new_i_deg = new_igrf_df["I_deg"].str.replace("d", "")
new_i_min = new_igrf_df["I_min"].str.replace("m", "")

In [8]:
# Put them into the dataframe
df_delete_words = new_igrf_df
df_delete_words["New_Altitude"] = new_altitude
df_delete_words["New_D_deg"] = new_d_deg
df_delete_words["New_D_min"] = new_d_min
df_delete_words["New_I_deg"] = new_i_deg
df_delete_words["New_I_min"] = new_i_min

In [9]:
# Create new dataframe
fixed_words_df = df_delete_words[["Code", "Date", "Latitude", "Longitude", "New_Altitude", "New_D_deg", "New_D_min", "New_I_deg", "New_I_min", "H_nT", "X_nT", "Y_nT", "Z_nT", "F_nT", "dD_min", "dI_min", "dH_nT", "dX_nT", "dY_nT", "dZ_nT", "dF_nT"]]

# View it
fixed_words_df

,Code,Date,Latitude,Longitude,New_Altitude,New_D_deg,New_D_min,New_I_deg,New_I_min,H_nT,...,Y_nT,Z_nT,F_nT,dD_min,dI_min,dH_nT,dX_nT,dY_nT,dZ_nT,dF_nT
0,AC_CZS,1958.529,-7.637,-72.670,182.464,2,47,11,10,29072.2,...,1412.5,5735.2,29632.5,-6.9,-3.1,-59.5,-56.7,-60.9,-38.5,-65.8
1,AC_CZS,1965.848,-7.637,-72.670,182.464,1,55,10,55,28605.3,...,959.8,5519.5,29132.9,-7.4,-0.8,-73.5,-71.5,-63.7,-20.8,-76.1
2,AC_CZS,1978.640,-7.620,-72.670,195.6,0,9,10,48,27813.9,...,72.2,5309.1,28316.1,-10.4,1.4,-46.8,-46.8,-84.3,2.4,-45.6
3,AC_CZS,1986.279,-7.599,-72.770,196.508,-1,5,10,33,27428.6,...,-520.7,5109.1,27900.4,-10.2,-4.3,-51.2,-52.9,-80.1,-44.6,-58.5
4,AC_CZS,1989.503,-7.599,-72.770,196.508,-1,38,10,19,27264.3,...,-778.9,4965.3,27712.7,-10.3,-4.3,-50.4,-52.9,-80.1,-44.6,-57.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,TO_PNL,1985.119,-10.727,-48.408,240.299,-18,5,-7,1,24935.1,...,-7741.6,-3070.7,25123.5,-6.3,-19.5,-58.2,-69.4,-25.0,-136.5,-40.6
1078,TO_PNL,1986.670,-10.727,-48.408,240.299,-18,15,-7,32,24844.9,...,-7780.4,-3282.4,25060.8,-6.3,-19.6,-58.0,-69.4,-25.0,-136.5,-39.2
1079,TO_PNL,1995.817,-10.727,-48.408,240.299,-19,15,-10,37,24299.2,...,-8009.9,-4551.7,24721.8,-6.1,-20.9,-60.2,-71.0,-20.9,-141.1,-32.7
1080,TO_PNL,2003.702,-10.721,-48.401,256.835,-20,2,-13,21,23824.7,...,-8162.8,-5656.0,24486.8,-5.9,-21.0,-60.5,-70.8,-17.2,-139.1,-26.3
1081,TO_RAB,1970.729,-9.242,-48.530,249.44,-16,0,0,-1,26131.5,...,-7204.4,-9.8,26131.5,-7.7,-15.5,-56.8,-70.7,-40.4,-117.6,-56.5

In [10]:
# Check dataaframe info
fixed_words_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1082 entries, 0 to 1081
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Code          1082 non-null   object
 1   Date          1082 non-null   float64
 2   Latitude      1082 non-null   float64
 3   Longitude     1082 non-null   float64
 4   New_Altitude  1082 non-null   object
 5   New_D_deg     1082 non-null   object
 6   New_D_min     1082 non-null   object
 7   New_I_deg     1082 non-null   object
 8   New_I_min     1082 non-null   object
 9   H_nT          1082 non-null   float64
 10  X_nT          1082 non-null   float64
 11  Y_nT          1082 non-null   float64
 12  Z_nT          1082 non-null   float64
 13  F_nT          1082 non-null   float64
 14  dD_min        1082 non-null   float64
 15  dI_min        1082 non-null   float64
 16  dH_nT         1082 non-null   float64
 17  dX_nT         1082 non-null   float64
 18  dY_nT         1082 non-null   float64
 19  dZ_nT         1082 non-null   float64
 20  dF_nT         1082 non-null   float64
dtypes: float64(15), object(6)
memory usage: 177.6+ KB

## Convert object types to float64 type

In [11]:
# Create df
numeric_df = fixed_words_df

# Convert
numeric_df = numeric_df.astype({"New_Altitude": float}, errors='raise')
numeric_df = numeric_df.astype({"New_D_deg": float}, errors='raise') 
numeric_df = numeric_df.astype({"New_D_min": float}, errors='raise')
numeric_df = numeric_df.astype({"New_I_deg": float}, errors='raise') 
numeric_df = numeric_df.astype({"New_I_min": float}, errors='raise')

# Check the changes
numeric_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1082 entries, 0 to 1081
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Code          1082 non-null   object
 1   Date          1082 non-null   float64
 2   Latitude      1082 non-null   float64
 3   Longitude     1082 non-null   float64
 4   New_Altitude  1082 non-null   float64
 5   New_D_deg     1082 non-null   float64
 6   New_D_min     1082 non-null   float64
 7   New_I_deg     1082 non-null   float64
 8   New_I_min     1082 non-null   float64
 9   H_nT          1082 non-null   float64
 10  X_nT          1082 non-null   float64
 11  Y_nT          1082 non-null   float64
 12  Z_nT          1082 non-null   float64
 13  F_nT          1082 non-null   float64
 14  dD_min        1082 non-null   float64
 15  dI_min        1082 non-null   float64
 16  dH_nT         1082 non-null   float64
 17  dX_nT         1082 non-null   float64
 18  dY_nT         1082 non-null   float64
 19  dZ_nT         1082 non-null   float64
 20  dF_nT         1082 non-null   float64
dtypes: float64(20), object(1)
memory usage: 177.6+ KB

## Mark the signal of each degree for D and I as positive or negative

In [12]:
# Create new df 
df_signal = numeric_df

# Create the columns to mark where the D_deg and I_deg are positive and negative
df_signal["D_signal"] = np.where(df_signal['New_D_deg'] >= 0,   'Positive', 'Negative')
df_signal["I_signal"] = np.where(df_signal['New_I_deg'] >= 0,   'Positive', 'Negative')

# Add the colums with the markers for D and I
df_dec_dpositivo = df_signal.loc[df_signal["D_signal"] == "Positive"]
df_dec_dnegativo = df_signal.loc[df_signal["D_signal"] == "Negative"]
df_inc_dpositivo = df_signal.loc[df_signal["I_signal"] == "Positive"]
df_inc_dnegativo = df_signal.loc[df_signal["I_signal"] == "Negative"]

# Check it
#df_signal

## Convert declination from dms to dd

In [13]:
# Create new dataframe
dec_calculation = df_signal

# Calulatoion
dec_pos_dd = mm.dms2dd_pos(df_dec_dpositivo["New_D_deg"], df_dec_dpositivo["New_D_min"], 0)
dec_neg_dd = mm.dms2dd_neg(df_dec_dnegativo["New_D_deg"], df_dec_dnegativo["New_D_min"], 0)

# Put result in the new datafgrame (positive first)
dec_calculation["IGRF_D_dd"] = dec_pos_dd

# check it
dec_calculation

,Code,Date,Latitude,Longitude,New_Altitude,New_D_deg,New_D_min,New_I_deg,New_I_min,H_nT,...,dD_min,dI_min,dH_nT,dX_nT,dY_nT,dZ_nT,dF_nT,D_signal,I_signal,IGRF_D_dd
0,AC_CZS,1958.529,-7.637,-72.670,182.464,2.0,47.0,11.0,10.0,29072.2,...,-6.9,-3.1,-59.5,-56.7,-60.9,-38.5,-65.8,Positive,Positive,2.783333
1,AC_CZS,1965.848,-7.637,-72.670,182.464,1.0,55.0,10.0,55.0,28605.3,...,-7.4,-0.8,-73.5,-71.5,-63.7,-20.8,-76.1,Positive,Positive,1.916667
2,AC_CZS,1978.640,-7.620,-72.670,195.600,0.0,9.0,10.0,48.0,27813.9,...,-10.4,1.4,-46.8,-46.8,-84.3,2.4,-45.6,Positive,Positive,0.150000
3,AC_CZS,1986.279,-7.599,-72.770,196.508,-1.0,5.0,10.0,33.0,27428.6,...,-10.2,-4.3,-51.2,-52.9,-80.1,-44.6,-58.5,Negative,Positive,NaN
4,AC_CZS,1989.503,-7.599,-72.770,196.508,-1.0,38.0,10.0,19.0,27264.3,...,-10.3,-4.3,-50.4,-52.9,-80.1,-44.6,-57.6,Negative,Positive,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,TO_PNL,1985.119,-10.727,-48.408,240.299,-18.0,5.0,-7.0,1.0,24935.1,...,-6.3,-19.5,-58.2,-69.4,-25.0,-136.5,-40.6,Negative,Negative,NaN
1078,TO_PNL,1986.670,-10.727,-48.408,240.299,-18.0,15.0,-7.0,32.0,24844.9,...,-6.3,-19.6,-58.0,-69.4,-25.0,-136.5,-39.2,Negative,Negative,NaN
1079,TO_PNL,1995.817,-10.727,-48.408,240.299,-19.0,15.0,-10.0,37.0,24299.2,...,-6.1,-20.9,-60.2,-71.0,-20.9,-141.1,-32.7,Negative,Negative,NaN
1080,TO_PNL,2003.702,-10.721,-48.401,256.835,-20.0,2.0,-13.0,21.0,23824.7,...,-5.9,-21.0,-60.5,-70.8,-17.2,-139.1,-26.3,Negative,Negative,NaN
1081,TO_RAB,1970.729,-9.242,-48.530,249.440,-16.0,0.0,0.0,-1.0,26131.5,...,-7.7,-15.5,-56.8,-70.7,-40.4,-117.6,-56.5,Negative,Positive,NaN

In [14]:
# Create list with the index values of NaN in the IGRF_Dec_dd column
igrf_dec_dd_nan = dec_calculation[dec_calculation["IGRF_D_dd"].isna()]
index_igrf_dec_dd_nan_list = igrf_dec_dd_nan["IGRF_D_dd"].index.tolist()

# Create new dataframe for calculated IGRF_Dec_dd values, replace NaN values with calculated ones: NEGATIVE VALUES NOW
dec_calculated = dec_calculation
dec_calculated.loc[index_igrf_dec_dd_nan_list, "IGRF_D_dd"] = dec_neg_dd

# View it
dec_calculated

,Code,Date,Latitude,Longitude,New_Altitude,New_D_deg,New_D_min,New_I_deg,New_I_min,H_nT,...,dD_min,dI_min,dH_nT,dX_nT,dY_nT,dZ_nT,dF_nT,D_signal,I_signal,IGRF_D_dd
0,AC_CZS,1958.529,-7.637,-72.670,182.464,2.0,47.0,11.0,10.0,29072.2,...,-6.9,-3.1,-59.5,-56.7,-60.9,-38.5,-65.8,Positive,Positive,2.783333
1,AC_CZS,1965.848,-7.637,-72.670,182.464,1.0,55.0,10.0,55.0,28605.3,...,-7.4,-0.8,-73.5,-71.5,-63.7,-20.8,-76.1,Positive,Positive,1.916667
2,AC_CZS,1978.640,-7.620,-72.670,195.600,0.0,9.0,10.0,48.0,27813.9,...,-10.4,1.4,-46.8,-46.8,-84.3,2.4,-45.6,Positive,Positive,0.150000
3,AC_CZS,1986.279,-7.599,-72.770,196.508,-1.0,5.0,10.0,33.0,27428.6,...,-10.2,-4.3,-51.2,-52.9,-80.1,-44.6,-58.5,Negative,Positive,-1.083333
4,AC_CZS,1989.503,-7.599,-72.770,196.508,-1.0,38.0,10.0,19.0,27264.3,...,-10.3,-4.3,-50.4,-52.9,-80.1,-44.6,-57.6,Negative,Positive,-1.633333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,TO_PNL,1985.119,-10.727,-48.408,240.299,-18.0,5.0,-7.0,1.0,24935.1,...,-6.3,-19.5,-58.2,-69.4,-25.0,-136.5,-40.6,Negative,Negative,-18.083333
1078,TO_PNL,1986.670,-10.727,-48.408,240.299,-18.0,15.0,-7.0,32.0,24844.9,...,-6.3,-19.6,-58.0,-69.4,-25.0,-136.5,-39.2,Negative,Negative,-18.250000
1079,TO_PNL,1995.817,-10.727,-48.408,240.299,-19.0,15.0,-10.0,37.0,24299.2,...,-6.1,-20.9,-60.2,-71.0,-20.9,-141.1,-32.7,Negative,Negative,-19.250000
1080,TO_PNL,2003.702,-10.721,-48.401,256.835,-20.0,2.0,-13.0,21.0,23824.7,...,-5.9,-21.0,-60.5,-70.8,-17.2,-139.1,-26.3,Negative,Negative,-20.033333
1081,TO_RAB,1970.729,-9.242,-48.530,249.440,-16.0,0.0,0.0,-1.0,26131.5,...,-7.7,-15.5,-56.8,-70.7,-40.4,-117.6,-56.5,Negative,Positive,-16.000000

In [15]:
# Save file to test it
#dec_calculated.to_csv(output_folder / "teste_dec.csv", index=False, float_format="%.3f")

## Convert inclination from dms to dd

In [16]:
# create df
inc_calculation = dec_calculated

# Calculation
inc_pos_dd = mm.dms2dd_pos(df_inc_dpositivo["New_I_deg"], df_inc_dpositivo["New_I_min"], 0)
inc_neg_dd = mm.dms2dd_neg(df_inc_dnegativo["New_I_deg"], df_inc_dnegativo["New_I_min"], 0)

# Put result in the new datafgrame (positive first)
inc_calculation["IGRF_I_dd"] = inc_pos_dd

# check it
inc_calculation

,Code,Date,Latitude,Longitude,New_Altitude,New_D_deg,New_D_min,New_I_deg,New_I_min,H_nT,...,dI_min,dH_nT,dX_nT,dY_nT,dZ_nT,dF_nT,D_signal,I_signal,IGRF_D_dd,IGRF_I_dd
0,AC_CZS,1958.529,-7.637,-72.670,182.464,2.0,47.0,11.0,10.0,29072.2,...,-3.1,-59.5,-56.7,-60.9,-38.5,-65.8,Positive,Positive,2.783333,11.166667
1,AC_CZS,1965.848,-7.637,-72.670,182.464,1.0,55.0,10.0,55.0,28605.3,...,-0.8,-73.5,-71.5,-63.7,-20.8,-76.1,Positive,Positive,1.916667,10.916667
2,AC_CZS,1978.640,-7.620,-72.670,195.600,0.0,9.0,10.0,48.0,27813.9,...,1.4,-46.8,-46.8,-84.3,2.4,-45.6,Positive,Positive,0.150000,10.800000
3,AC_CZS,1986.279,-7.599,-72.770,196.508,-1.0,5.0,10.0,33.0,27428.6,...,-4.3,-51.2,-52.9,-80.1,-44.6,-58.5,Negative,Positive,-1.083333,10.550000
4,AC_CZS,1989.503,-7.599,-72.770,196.508,-1.0,38.0,10.0,19.0,27264.3,...,-4.3,-50.4,-52.9,-80.1,-44.6,-57.6,Negative,Positive,-1.633333,10.316667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,TO_PNL,1985.119,-10.727,-48.408,240.299,-18.0,5.0,-7.0,1.0,24935.1,...,-19.5,-58.2,-69.4,-25.0,-136.5,-40.6,Negative,Negative,-18.083333,NaN
1078,TO_PNL,1986.670,-10.727,-48.408,240.299,-18.0,15.0,-7.0,32.0,24844.9,...,-19.6,-58.0,-69.4,-25.0,-136.5,-39.2,Negative,Negative,-18.250000,NaN
1079,TO_PNL,1995.817,-10.727,-48.408,240.299,-19.0,15.0,-10.0,37.0,24299.2,...,-20.9,-60.2,-71.0,-20.9,-141.1,-32.7,Negative,Negative,-19.250000,NaN
1080,TO_PNL,2003.702,-10.721,-48.401,256.835,-20.0,2.0,-13.0,21.0,23824.7,...,-21.0,-60.5,-70.8,-17.2,-139.1,-26.3,Negative,Negative,-20.033333,NaN
1081,TO_RAB,1970.729,-9.242,-48.530,249.440,-16.0,0.0,0.0,-1.0,26131.5,...,-15.5,-56.8,-70.7,-40.4,-117.6,-56.5,Negative,Positive,-16.000000,-0.016667

In [17]:
# Create list with the index values of NaN in the IGRF_Dec_dd column
igrf_inc_dd_nan = inc_calculation[inc_calculation["IGRF_I_dd"].isna()]
index_igrf_inc_dd_nan_list = igrf_inc_dd_nan["IGRF_I_dd"].index.tolist()

# Create new dataframe for calculated IGRF_Dec_dd values, replace NaN values with calculated ones: NEGATIVE VALUES NOW
inc_calculated = inc_calculation
inc_calculated.loc[index_igrf_inc_dd_nan_list, "IGRF_I_dd"] = inc_neg_dd

# View it
inc_calculated

,Code,Date,Latitude,Longitude,New_Altitude,New_D_deg,New_D_min,New_I_deg,New_I_min,H_nT,...,dI_min,dH_nT,dX_nT,dY_nT,dZ_nT,dF_nT,D_signal,I_signal,IGRF_D_dd,IGRF_I_dd
0,AC_CZS,1958.529,-7.637,-72.670,182.464,2.0,47.0,11.0,10.0,29072.2,...,-3.1,-59.5,-56.7,-60.9,-38.5,-65.8,Positive,Positive,2.783333,11.166667
1,AC_CZS,1965.848,-7.637,-72.670,182.464,1.0,55.0,10.0,55.0,28605.3,...,-0.8,-73.5,-71.5,-63.7,-20.8,-76.1,Positive,Positive,1.916667,10.916667
2,AC_CZS,1978.640,-7.620,-72.670,195.600,0.0,9.0,10.0,48.0,27813.9,...,1.4,-46.8,-46.8,-84.3,2.4,-45.6,Positive,Positive,0.150000,10.800000
3,AC_CZS,1986.279,-7.599,-72.770,196.508,-1.0,5.0,10.0,33.0,27428.6,...,-4.3,-51.2,-52.9,-80.1,-44.6,-58.5,Negative,Positive,-1.083333,10.550000
4,AC_CZS,1989.503,-7.599,-72.770,196.508,-1.0,38.0,10.0,19.0,27264.3,...,-4.3,-50.4,-52.9,-80.1,-44.6,-57.6,Negative,Positive,-1.633333,10.316667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,TO_PNL,1985.119,-10.727,-48.408,240.299,-18.0,5.0,-7.0,1.0,24935.1,...,-19.5,-58.2,-69.4,-25.0,-136.5,-40.6,Negative,Negative,-18.083333,-7.016667
1078,TO_PNL,1986.670,-10.727,-48.408,240.299,-18.0,15.0,-7.0,32.0,24844.9,...,-19.6,-58.0,-69.4,-25.0,-136.5,-39.2,Negative,Negative,-18.250000,-7.533333
1079,TO_PNL,1995.817,-10.727,-48.408,240.299,-19.0,15.0,-10.0,37.0,24299.2,...,-20.9,-60.2,-71.0,-20.9,-141.1,-32.7,Negative,Negative,-19.250000,-10.616667
1080,TO_PNL,2003.702,-10.721,-48.401,256.835,-20.0,2.0,-13.0,21.0,23824.7,...,-21.0,-60.5,-70.8,-17.2,-139.1,-26.3,Negative,Negative,-20.033333,-13.350000
1081,TO_RAB,1970.729,-9.242,-48.530,249.440,-16.0,0.0,0.0,-1.0,26131.5,...,-15.5,-56.8,-70.7,-40.4,-117.6,-56.5,Negative,Positive,-16.000000,-0.016667

## Save file

In [18]:
# Create new main dataframe for IGRF13 values
igrf_database = inc_calculated

In [19]:
# Change column names
igrf_database = igrf_database.rename(
    columns={
        "New_Altitude": "Alitude_m",
        "New_D_deg": "IGRF_D_deg",
        "New_D_min": "IGRF_D_min",
        "New_I_deg": "IGRF_I_deg",
        "New_I_min": "IGRF_I_min",
        "H_nT": "IGRF_H_nT",
        "X_nT": "IGRF_X_nT",
        "Y_nT": "IGRF_Y_nT",
        "Z_nT": "IGRF_Z_nT",
        "F_nT": "IGRF_F_nT",
        "dD_min": "IGRF_dD_min",
        "dI_min": "IGRF_dI_min",
        "dH_nT": "IGRF_dH_nT",
        "dX_nT": "IGRF_dX_nT",
        "dY_nT": "IGRF_dY_nT",
        "dZ_nT": "IGRF_dZ_nT",
        "dF_nT": "IGRF_dF_nT",
    }
)
igrf_database

,Code,Date,Latitude,Longitude,Alitude_m,IGRF_D_deg,IGRF_D_min,IGRF_I_deg,IGRF_I_min,IGRF_H_nT,...,IGRF_dI_min,IGRF_dH_nT,IGRF_dX_nT,IGRF_dY_nT,IGRF_dZ_nT,IGRF_dF_nT,D_signal,I_signal,IGRF_D_dd,IGRF_I_dd
0,AC_CZS,1958.529,-7.637,-72.670,182.464,2.0,47.0,11.0,10.0,29072.2,...,-3.1,-59.5,-56.7,-60.9,-38.5,-65.8,Positive,Positive,2.783333,11.166667
1,AC_CZS,1965.848,-7.637,-72.670,182.464,1.0,55.0,10.0,55.0,28605.3,...,-0.8,-73.5,-71.5,-63.7,-20.8,-76.1,Positive,Positive,1.916667,10.916667
2,AC_CZS,1978.640,-7.620,-72.670,195.600,0.0,9.0,10.0,48.0,27813.9,...,1.4,-46.8,-46.8,-84.3,2.4,-45.6,Positive,Positive,0.150000,10.800000
3,AC_CZS,1986.279,-7.599,-72.770,196.508,-1.0,5.0,10.0,33.0,27428.6,...,-4.3,-51.2,-52.9,-80.1,-44.6,-58.5,Negative,Positive,-1.083333,10.550000
4,AC_CZS,1989.503,-7.599,-72.770,196.508,-1.0,38.0,10.0,19.0,27264.3,...,-4.3,-50.4,-52.9,-80.1,-44.6,-57.6,Negative,Positive,-1.633333,10.316667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,TO_PNL,1985.119,-10.727,-48.408,240.299,-18.0,5.0,-7.0,1.0,24935.1,...,-19.5,-58.2,-69.4,-25.0,-136.5,-40.6,Negative,Negative,-18.083333,-7.016667
1078,TO_PNL,1986.670,-10.727,-48.408,240.299,-18.0,15.0,-7.0,32.0,24844.9,...,-19.6,-58.0,-69.4,-25.0,-136.5,-39.2,Negative,Negative,-18.250000,-7.533333
1079,TO_PNL,1995.817,-10.727,-48.408,240.299,-19.0,15.0,-10.0,37.0,24299.2,...,-20.9,-60.2,-71.0,-20.9,-141.1,-32.7,Negative,Negative,-19.250000,-10.616667
1080,TO_PNL,2003.702,-10.721,-48.401,256.835,-20.0,2.0,-13.0,21.0,23824.7,...,-21.0,-60.5,-70.8,-17.2,-139.1,-26.3,Negative,Negative,-20.033333,-13.350000
1081,TO_RAB,1970.729,-9.242,-48.530,249.440,-16.0,0.0,0.0,-1.0,26131.5,...,-15.5,-56.8,-70.7,-40.4,-117.6,-56.5,Negative,Positive,-16.000000,-0.016667

In [20]:
# Save the IGRF database
igrf_database.to_csv(output_folder / output_file, index=False, float_format="%.3f")