# Create a database with values from the repeat stations and IGRF13

## Description

This program creates the database from repeat station and IGRF data

In [1]:
# Import modules
import mestrado_module as mm
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt

In [2]:
# Defitions for input and output

# Input repeat stations
input_rs_folder: Path = Path(mm.path_pipeline_03_rs_database_creation)
input_rs_file: Path = Path(mm.output_3_code_rs_database)

# Station list
input_list_stations_folder: Path = Path(mm.path_pipeline_03_rs_database_creation)
input_list_stations_file: Path = Path(mm.output_3_code_ocp_list)

# Input IGRF values
input_igrf_folder: Path = Path(mm.path_pipeline_04_igrf_calc)
input_igrf_file: Path = Path(mm.output_4c_code_igrf_database)

# Output
output_folder: Path = Path(mm.path_pipeline_04_igrf_calc)
output_file: Path = Path(mm.output_4d_code_rs_igrf_database)
err_db: Path = Path(mm.output_4d_code_error_database)

## Read data

In [3]:
# Load station and IGRF data with Pandas
rs_df = pd.read_csv(input_rs_folder / input_rs_file)
rs_df

,Code,Lat_dd,Lon_dd,Alt_m,Time_dy,D_dd,I_dd,H_nT,X_nT,Y_nT,...,State,Region,RS_name,Calculated_X,Calculated_Y,Calculated_Z,TTB_distances_km,VSS_distances_km,Closest_OBS,N_occupations
0,AC_CZS,-7.637,-72.670,182.464,1958.529,2.683,11.281,29097.0,29065.0,1362.0,...,AC,N,CRUZEIRO DO SUL,29065.847,1362.067,5804.269,2770.494,3511.151,TTB,6
1,AC_CZS,-7.637,-72.670,182.464,1965.848,1.824,11.277,28662.0,28648.0,912.0,...,AC,N,CRUZEIRO DO SUL,28648.198,912.318,5715.412,2770.494,3511.151,TTB,6
2,AC_CZS,-7.620,-72.670,195.600,1978.640,-0.035,11.026,27835.0,27835.0,-17.0,...,AC,N,CRUZEIRO DO SUL,27835.502,-17.004,5423.784,2770.044,3512.127,TTB,6
3,AC_CZS,-7.599,-72.770,196.508,1986.279,-1.343,10.685,27402.0,27394.0,-642.0,...,AC,N,CRUZEIRO DO SUL,27394.968,-642.249,5170.325,2780.199,3522.772,TTB,6
4,AC_CZS,-7.599,-72.770,196.508,1989.503,-1.847,10.468,27222.0,27208.0,-877.0,...,AC,N,CRUZEIRO DO SUL,27208.116,-877.391,5029.623,2780.199,3522.772,TTB,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,TO_PNL,-10.727,-48.408,240.299,1985.119,-18.142,-7.084,24938.0,23698.0,-7765.0,...,TO,N,PORTO NACIONAL,23698.435,-7765.075,-3099.141,1058.862,1393.116,TTB,9
1078,TO_PNL,-10.727,-48.408,240.299,1986.670,-18.325,-7.556,24865.0,23604.0,-7817.0,...,TO,N,PORTO NACIONAL,23604.245,-7817.785,-3298.293,1058.862,1393.116,TTB,9
1079,TO_PNL,-10.727,-48.408,240.299,1995.817,-19.315,-10.562,24358.0,22987.0,-8056.0,...,TO,N,PORTO NACIONAL,22987.174,-8056.751,-4541.793,1058.862,1393.116,TTB,9
1080,TO_PNL,-10.721,-48.401,256.835,2003.702,-20.117,-13.008,23896.0,22438.0,-8218.0,...,TO,N,PORTO NACIONAL,22438.750,-8218.967,-5520.486,1058.203,1393.470,TTB,9
1081,TO_RAB,-9.242,-48.530,249.440,1970.729,-16.148,0.093,26189.0,25156.0,-7283.0,...,TO,N,RIBEIRAO DA AGUA BRANCA,25156.680,-7283.939,42.510,893.676,1552.975,TTB,1

In [4]:
# Load station and IGRF data with Pandas
igrf_df = pd.read_csv(input_igrf_folder / input_igrf_file)
igrf_df

,Code,Date,Latitude,Longitude,Alitude_m,IGRF_D_deg,IGRF_D_min,IGRF_I_deg,IGRF_I_min,IGRF_H_nT,...,IGRF_dI_min,IGRF_dH_nT,IGRF_dX_nT,IGRF_dY_nT,IGRF_dZ_nT,IGRF_dF_nT,D_signal,I_signal,IGRF_D_dd,IGRF_I_dd
0,AC_CZS,1958.529,-7.637,-72.670,182.464,2.0,47.0,11.0,10.0,29072.2,...,-3.1,-59.5,-56.7,-60.9,-38.5,-65.8,Positive,Positive,2.783,11.167
1,AC_CZS,1965.848,-7.637,-72.670,182.464,1.0,55.0,10.0,55.0,28605.3,...,-0.8,-73.5,-71.5,-63.7,-20.8,-76.1,Positive,Positive,1.917,10.917
2,AC_CZS,1978.640,-7.620,-72.670,195.600,0.0,9.0,10.0,48.0,27813.9,...,1.4,-46.8,-46.8,-84.3,2.4,-45.6,Positive,Positive,0.150,10.800
3,AC_CZS,1986.279,-7.599,-72.770,196.508,-1.0,5.0,10.0,33.0,27428.6,...,-4.3,-51.2,-52.9,-80.1,-44.6,-58.5,Negative,Positive,-1.083,10.550
4,AC_CZS,1989.503,-7.599,-72.770,196.508,-1.0,38.0,10.0,19.0,27264.3,...,-4.3,-50.4,-52.9,-80.1,-44.6,-57.6,Negative,Positive,-1.633,10.317
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,TO_PNL,1985.119,-10.727,-48.408,240.299,-18.0,5.0,-7.0,1.0,24935.1,...,-19.5,-58.2,-69.4,-25.0,-136.5,-40.6,Negative,Negative,-18.083,-7.017
1078,TO_PNL,1986.670,-10.727,-48.408,240.299,-18.0,15.0,-7.0,32.0,24844.9,...,-19.6,-58.0,-69.4,-25.0,-136.5,-39.2,Negative,Negative,-18.250,-7.533
1079,TO_PNL,1995.817,-10.727,-48.408,240.299,-19.0,15.0,-10.0,37.0,24299.2,...,-20.9,-60.2,-71.0,-20.9,-141.1,-32.7,Negative,Negative,-19.250,-10.617
1080,TO_PNL,2003.702,-10.721,-48.401,256.835,-20.0,2.0,-13.0,21.0,23824.7,...,-21.0,-60.5,-70.8,-17.2,-139.1,-26.3,Negative,Negative,-20.033,-13.350
1081,TO_RAB,1970.729,-9.242,-48.530,249.440,-16.0,0.0,0.0,-1.0,26131.5,...,-15.5,-56.8,-70.7,-40.4,-117.6,-56.5,Negative,Positive,-16.000,-0.017

## Create a dataframe with repeat station data and IGRF values

In [5]:
# create a new dataframe to work on
main_db = rs_df
main_db["IGRF_D_dd"] = igrf_df["IGRF_D_dd"]
main_db["IGRF_I_dd"] = igrf_df["IGRF_I_dd"]
main_db["IGRF_F_nT"] = igrf_df["IGRF_F_nT"]
main_db["IGRF_H_nT"] = igrf_df["IGRF_H_nT"]
main_db["IGRF_X_nT"] = igrf_df["IGRF_X_nT"]
main_db["IGRF_Y_nT"] = igrf_df["IGRF_Y_nT"]
main_db["IGRF_Z_nT"] = igrf_df["IGRF_Z_nT"]

main_db

,Code,Lat_dd,Lon_dd,Alt_m,Time_dy,D_dd,I_dd,H_nT,X_nT,Y_nT,...,VSS_distances_km,Closest_OBS,N_occupations,IGRF_D_dd,IGRF_I_dd,IGRF_F_nT,IGRF_H_nT,IGRF_X_nT,IGRF_Y_nT,IGRF_Z_nT
0,AC_CZS,-7.637,-72.670,182.464,1958.529,2.683,11.281,29097.0,29065.0,1362.0,...,3511.151,TTB,6,2.783,11.167,29632.5,29072.2,29037.9,1412.5,5735.2
1,AC_CZS,-7.637,-72.670,182.464,1965.848,1.824,11.277,28662.0,28648.0,912.0,...,3511.151,TTB,6,1.917,10.917,29132.9,28605.3,28589.2,959.8,5519.5
2,AC_CZS,-7.620,-72.670,195.600,1978.640,-0.035,11.026,27835.0,27835.0,-17.0,...,3512.127,TTB,6,0.150,10.800,28316.1,27813.9,27813.8,72.2,5309.1
3,AC_CZS,-7.599,-72.770,196.508,1986.279,-1.343,10.685,27402.0,27394.0,-642.0,...,3522.772,TTB,6,-1.083,10.550,27900.4,27428.6,27423.6,-520.7,5109.1
4,AC_CZS,-7.599,-72.770,196.508,1989.503,-1.847,10.468,27222.0,27208.0,-877.0,...,3522.772,TTB,6,-1.633,10.317,27712.7,27264.3,27253.2,-778.9,4965.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,TO_PNL,-10.727,-48.408,240.299,1985.119,-18.142,-7.084,24938.0,23698.0,-7765.0,...,1393.116,TTB,9,-18.083,-7.017,25123.5,24935.1,23702.9,-7741.6,-3070.7
1078,TO_PNL,-10.727,-48.408,240.299,1986.670,-18.325,-7.556,24865.0,23604.0,-7817.0,...,1393.116,TTB,9,-18.250,-7.533,25060.8,24844.9,23595.3,-7780.4,-3282.4
1079,TO_PNL,-10.727,-48.408,240.299,1995.817,-19.315,-10.562,24358.0,22987.0,-8056.0,...,1393.116,TTB,9,-19.250,-10.617,24721.8,24299.2,22941.0,-8009.9,-4551.7
1080,TO_PNL,-10.721,-48.401,256.835,2003.702,-20.117,-13.008,23896.0,22438.0,-8218.0,...,1393.470,TTB,9,-20.033,-13.350,24486.8,23824.7,22382.6,-8162.8,-5656.0
1081,TO_RAB,-9.242,-48.530,249.440,1970.729,-16.148,0.093,26189.0,25156.0,-7283.0,...,1552.975,TTB,1,-16.000,-0.017,26131.5,26131.5,25118.8,-7204.4,-9.8

In [6]:
# Organize main database
main_db = main_db[["Code", "Lat_dd", "Lon_dd", "Alt_m", "Time_dy", "D_dd", "IGRF_D_dd", "I_dd", "IGRF_I_dd",
                   "F_nT", "IGRF_F_nT", "H_nT", "IGRF_H_nT", "X_nT", "IGRF_X_nT", "Calculated_X",
                   "Y_nT", "IGRF_Y_nT", "Calculated_Y", "Z_nT", "IGRF_Z_nT", "Calculated_Z",
                   "N_occupations", "Closest_OBS", "TTB_distances_km", "VSS_distances_km",
                   "State", "Region", "RS_name"]]

# view
main_db

,Code,Lat_dd,Lon_dd,Alt_m,Time_dy,D_dd,IGRF_D_dd,I_dd,IGRF_I_dd,F_nT,...,Z_nT,IGRF_Z_nT,Calculated_Z,N_occupations,Closest_OBS,TTB_distances_km,VSS_distances_km,State,Region,RS_name
0,AC_CZS,-7.637,-72.670,182.464,1958.529,2.683,2.783,11.281,11.167,29671.0,...,5804.0,5735.2,5804.269,6,TTB,2770.494,3511.151,AC,N,CRUZEIRO DO SUL
1,AC_CZS,-7.637,-72.670,182.464,1965.848,1.824,1.917,11.277,10.917,29227.0,...,5715.0,5519.5,5715.412,6,TTB,2770.494,3511.151,AC,N,CRUZEIRO DO SUL
2,AC_CZS,-7.620,-72.670,195.600,1978.640,-0.035,0.150,11.026,10.800,28359.0,...,5423.0,5309.1,5423.784,6,TTB,2770.044,3512.127,AC,N,CRUZEIRO DO SUL
3,AC_CZS,-7.599,-72.770,196.508,1986.279,-1.343,-1.083,10.685,10.550,27886.0,...,5170.0,5109.1,5170.325,6,TTB,2780.199,3522.772,AC,N,CRUZEIRO DO SUL
4,AC_CZS,-7.599,-72.770,196.508,1989.503,-1.847,-1.633,10.468,10.317,27683.0,...,5029.0,4965.3,5029.623,6,TTB,2780.199,3522.772,AC,N,CRUZEIRO DO SUL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1077,TO_PNL,-10.727,-48.408,240.299,1985.119,-18.142,-18.083,-7.084,-7.017,25130.0,...,-3099.0,-3070.7,-3099.141,9,TTB,1058.862,1393.116,TO,N,PORTO NACIONAL
1078,TO_PNL,-10.727,-48.408,240.299,1986.670,-18.325,-18.250,-7.556,-7.533,25083.0,...,-3298.0,-3282.4,-3298.293,9,TTB,1058.862,1393.116,TO,N,PORTO NACIONAL
1079,TO_PNL,-10.727,-48.408,240.299,1995.817,-19.315,-19.250,-10.562,-10.617,24778.0,...,-4541.0,-4551.7,-4541.793,9,TTB,1058.862,1393.116,TO,N,PORTO NACIONAL
1080,TO_PNL,-10.721,-48.401,256.835,2003.702,-20.117,-20.033,-13.008,-13.350,24526.0,...,-5520.0,-5656.0,-5520.486,9,TTB,1058.203,1393.470,TO,N,PORTO NACIONAL
1081,TO_RAB,-9.242,-48.530,249.440,1970.729,-16.148,-16.000,0.093,-0.017,26190.0,...,42.0,-9.8,42.510,1,TTB,893.676,1552.975,TO,N,RIBEIRAO DA AGUA BRANCA

## Create the database: Repeat Stations and IGRF values

In [7]:
# Save database
main_db.to_csv(output_folder / output_file, index=False, float_format="%.3f", na_rep="NaN")